### ISSUE TITLE
LAB_04_Configure and integrate a Log Analytics agent and workspace in Defender for Cloud.md

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/Secure-Azure-services-and-workloads-with-Microsoft-Defender-for-Cloud-regulatory-compliance-controls#10]
# Module: 00
#### Step: 00

Description of issue

**- Task 'Configure integration with the Log Analytics agent'/Step 5:** UI appears to have changed since instructions written, after clicking Settings & Monitoring' there are multiple 'Edit configuration' options.  I *think* the one that needs to be called out for this task is the 'Log Analytics agent' row.

**Comment by serling1962** [comment]
Edits applied.
