### ISSUE TITLE
LAB_05b_Perform soft-delete and purge protection key vault recovery.md

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/Secure-Azure-services-and-workloads-with-Microsoft-Defender-for-Cloud-regulatory-compliance-controls#11]
# Module: 00
#### Step: 00

Description of issue

**- Task 'List, recover, or purge a soft-deleted key vault'/Step 7-11:** While the instructions are generic enough '_If_ there are too many vaults', '_if_ you would like to recover', and similar, but at least in a Cloudslice config it is not apparent that individual lab launches are going to have *any* deleted key vaults, and since the instructions seem to imply to students that they will see deleted vaults, this will likely lead to support tickets asking 'where are the deleted vaults?'.   Recommend including the steps to delete a sample key vault earlier in this lab, if it is desired to have students actually undelete a vault.

**- Task 'List, recover, or purge soft-deleted secrets, keys, and certificates'/Step 3-8:** Same issue as above.

**Comment by serling1962** [comment]
Not an issue.  The lab is intended to provide practical understanding.
