### ISSUE TITLE
LAB_06_Connect to an Azure SQL server using an Azure Private Endpoint using the Azure portal.md

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/Secure-Azure-services-and-workloads-with-Microsoft-Defender-for-Cloud-regulatory-compliance-controls#12]
# Module: 00
#### Step: 00

Description of issue

**- Task 'Create an Azure SQL server and private endpoint'/Step 4:** Because the default workload environment and compute + storage defaults apparently will pick a *very* costly SQL server - and this horsepower/$$ cost is not remotely needed for the demo done in this lab later, recommend elaborating on that step to specify a 'Development' workload selected, and 'Configure database' to specifically select a much more modest SQL server -  A good choice might be 'Basic':

![image](https://github.com/MicrosoftLearning/Secure-Azure-services-and-workloads-with-Microsoft-Defender-for-Cloud-regulatory-compliance-controls/assets/49700217/6f066a42-e060-43c6-b8c9-944ff21d525e)

**- Task 'Create an Azure SQL server and private endpoint'/Step 8:**  In the table, entry 'Target sub-resource' should say 'SqlServer' and not the SQL servers name.

**- Task 'Test connectivity to private endpoint'/Step 6:**  After clicking 'Connect', a warning is given in a default Edge browser config indicating 'A popup blocker is preventing new window from opening.  Please allow popups and retry'.  Recommend including a step or note confirming one should go to Edge settings/Pop-ups and redirects/and switch the 'Blocked' switch to off, before selecting 'Connect'.

**Comment by serling1962** [comment]
The instance noted is for training purposes only.  The ask to apply the target sub-resource name as noted in the training instruction is valid.
