### ISSUE TITLE
LAB_01_Create a virtual network infrastructure.md

### ISSUE THREAD

**Issue by gorlandor** [MicrosoftLearning/Secure-Azure-services-and-workloads-with-Microsoft-Defender-for-Cloud-regulatory-compliance-controls#13]
# Module: 00
#### Step: 00

Description of issue

The Virtual Network is created in the East US 2 region. Instructions for the Application Security Groups, Network Security Groups, and Virtual Machines say these are to be deployed to East US region. Image [here](https://github.com/MicrosoftLearning/Secure-Azure-services-and-workloads-with-Microsoft-Cloud-Security-Benchmark/assets/91347931/c32ef7df-306a-4b01-942d-da7325d8f10a) confirms that the Virtual Machine is meant to be on East US 2. Network security groups can only be associated to subnets whose virtual network is in the same subscription and region.

The region in the instructions for the Application Security Groups, Network Security Groups, and Virtual Machines should be updated from ~East US~ to East US 2 to match the Virtual Network. 

For reference:  
<img width="1230" alt="Screenshot 2023-10-29 at 10 47 26 AM" src="https://github.com/MicrosoftLearning/Secure-Azure-services-and-workloads-with-Microsoft-Defender-for-Cloud-regulatory-compliance-controls/assets/11283367/273d3121-f86e-426b-a2b4-14a32a1b512c"> <br/>

Repro steps:

1. Create ASG and NSG in a different region than the Virtual Network
2. Follow instructions to create the NSG rules using the ASG.
3. Go to nsg-1 > Subnets > Associate
4. Confirm the Virtual Network is not available for selection.
5. Go to vnet-1 > Subnets > subnet-1 > Network security group
6. Confirm the NSG from the different region is not available for selection.
7. Attempt to create Virtual Machine in a different region than the Virtual Network.
8. In the Networking tab of the Virtual Machine deployment, confirm the Virtual Network in different region is not available for selection

**Comment by serling1962** [comment]
Edits were applied.  Note: APL-5002 lab exercised are intended to be used via BYOS.  **At this time** APL 5002 exercises have not been tested in Skillable Cloud Slice.
