### ISSUE TITLE
LAB_01_Create a virtual network infrastructure.md

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/Secure-Azure-services-and-workloads-with-Microsoft-Defender-for-Cloud-regulatory-compliance-controls#8]
# Module: 00
#### Step: 00

Description of issue

**- 'Create two virtual machines (VMs) in the virtual network you created earlier.'/Step 4**: Subnet to choose is listed as 'default (10.0.0.0/24)', however earlier in the lab we changed that name to 'subnet-1'.  Should update name in this step as well to 'subnet-1'.

**Comment by serling1962** [comment]
Edits applied.
