### ISSUE TITLE
LAB_03b_Configure just-in-time (JIT) VM access in Defender for Cloud.md

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/Secure-Azure-services-and-workloads-with-Microsoft-Defender-for-Cloud-regulatory-compliance-controls#9]
# Module: 00
#### Step: 00

Description of issue

**- Task 'Enable JIT on your VMs from Microsoft Defender for Cloud'/Step 3:** This section of the lab seems to have a combination of 'azure UI has changed', invalidating the step-by-step in the instructions, possibly aggravated by the time it takes Azure to actually *enable* the Defender settings?  In QA'ing this lab using Cloudslice I found some possible 'fixes' but I am not a Defender expert, there may be better solutions the CO can identify.

More details of this step/issue:

There is no ‘Just-in-time VM access’, instead I see an indicator it is not enabled:

![image](https://github.com/MicrosoftLearning/Secure-Azure-services-and-workloads-with-Microsoft-Defender-for-Cloud-regulatory-compliance-controls/assets/49700217/b14111e0-eb57-47f2-aab9-e7efb9423bbf)

-If I do not take any additional actions and just wait for a long period of time – 10-15 minutes – to allow any backend processes to proceed, the above screen does not change.

-If I select ‘Enable Microsoft Defender for Cloud’ on that screen, and also wait for it to take effect, it takes me back to the screen where I had previous selected ‘Upgrade’ and I can select that again.  (It gives me another message that ‘Trial started’, although ‘Install agents’ is greyed out.

-Returning to the Workload protections screen does not change.

The only way I have found to workaround this issue is to go to Management/Environment Settings, and drill down to & select the MOC Sub:

![image](https://github.com/MicrosoftLearning/Secure-Azure-services-and-workloads-with-Microsoft-Defender-for-Cloud-regulatory-compliance-controls/assets/49700217/81f049a2-49a4-4e8c-b90e-af2f2b1bbf6d)

-From the resulting Settings/Defender plans page, select ‘Enable all plans’ and then ‘Save’:

![image](https://github.com/MicrosoftLearning/Secure-Azure-services-and-workloads-with-Microsoft-Defender-for-Cloud-regulatory-compliance-controls/assets/49700217/ef5f0dff-b211-4cf3-871b-90046168a1ec)

-Even with all of the above successful, returning to Workload protections now is populated & allows me to click the ‘Just-in-time VM access’, however it still seems like I have to go to the VMs to enable manually here:
(they appear as ‘unsupported’)

![image](https://github.com/MicrosoftLearning/Secure-Azure-services-and-workloads-with-Microsoft-Defender-for-Cloud-regulatory-compliance-controls/assets/49700217/b6c56203-f50a-455e-8824-893fafcbb258)

-Lastly, I needed to go to the individual VMs/Settings/Configuration and enable it here:

![image](https://github.com/MicrosoftLearning/Secure-Azure-services-and-workloads-with-Microsoft-Defender-for-Cloud-regulatory-compliance-controls/assets/49700217/3e17c1f9-6169-4404-9d5b-84ce5f3557d3)

-Unfortunately, even with this enabled, the Defender UI and behavior seems to have also changed enough that the balance of the instructions for this Task (‘Edit the JIT configuration on a JIT-enabled VM using Defender for Cloud’) cannot be followed verbatim.

**Comment by serling1962** [comment]
The instructions have been tested as intended in BYOS only.
